# Tensor Operations with Pytorch

In [2]:
from __future__ import print_function
import torch

## Creating Tensors

#### Manually Create Tensor

In [15]:
x = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
print(x)
print(x.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])


#### Randomly initialized 5x3 tensor

In [16]:
x = torch.rand(5, 3)
print(x)
print(x.shape)

tensor([[0.3304, 0.7667, 0.5864],
        [0.0328, 0.0606, 0.1283],
        [0.5433, 0.9204, 0.1465],
        [0.6370, 0.1960, 0.6566],
        [0.0114, 0.8163, 0.5968]])
torch.Size([5, 3])


#### 5x3 tensor of zeros

In [17]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.shape)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.Size([5, 3])


## Element Access

In [18]:
x = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

#### Get single element at 3rd row, 2nd column

In [19]:
x[2, 1]

tensor(8)

#### Get entire 4th row

In [20]:
x[3, :]

tensor([10, 11, 12])

#### Get entire 3rd column

In [21]:
x[:, 2]

tensor([ 3,  6,  9, 12])

#### Get all elements greater than 5

In [22]:
x[x > 5]

tensor([ 6,  7,  8,  9, 10, 11, 12])

## Tensor Arithmetic

In [26]:
print(x)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


#### Add 5 to every element in tensor

In [24]:
x+5

tensor([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

#### Broadcast addition with another tensor

In [27]:
b = torch.tensor([1, 2, 3])
torch.add(x, b)

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12],
        [11, 13, 15]])

#### Sum of all elements in tensor

In [28]:
torch.sum(x)

tensor(78)

#### Sum of elements row-wise

In [33]:
torch.sum(x, dim=1)

tensor([ 6, 15, 24, 33])

#### Reshaping Tensor to 4x3

In [35]:
x.reshape(3, 4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

#### Transpose tensor

In [36]:
torch.transpose(x, 0, 1)

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

## Dealing with Multiple Tensors

In [39]:
a = torch.tensor([[1, 2, 3],
                 [4, 5, 6]])
b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])
print(a)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


#### Subtract tensors

In [40]:
b - a

tensor([[6, 6, 6],
        [6, 6, 6]])

#### Matrix multiplication

In [44]:
print(torch.transpose(b, 0, 1))
torch.matmul(a, torch.transpose(b, 0, 1))

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


tensor([[ 50,  68],
        [122, 167]])

#### Concatenating two tensors

In [45]:
torch.cat((a, b))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

#### Stacking two tensors

In [49]:
torch.stack((a, b))

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

## Autograd

#### Accumulate Gradient

In [11]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [12]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [13]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


#### Backprop Gradient

In [14]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
